### ISSUE TITLE
Vertical Speed in m/h seems odd

### ISSUE THREAD

**Issue by mff73** [jimmykane/quantified-self#159] opened 2019-06-06 16:53 UTC
Hi,
This activity show around 10m/min max in SA --> 600m/h :)
but on Quantified, it shows 0.066m/h (divided by 1000 ? )
https://beta.quantified-self.io/user/FdFZssIbtodHP99WkN7GhhHjOCX2/event/3cPQA91MbTn2CvY9kk3FdUnL5VnvSriqHjVU1BLjAwveu4V
![image](https://user-images.githubusercontent.com/50132146/59051089-5ab32680-888c-11e9-947a-27803aca0297.png)

![image](https://user-images.githubusercontent.com/50132146/59050898-da8cc100-888b-11e9-9803-e9bb72f4ca6d.png)

**Comment by jimmykane** [comment] 2019-06-06 18:54
Hey thanks for this finding. I have been buggered about this since some years but never found a proper way to reproduce it. But now I know better. I ll get back to this when it's fixed.

**Comment by jimmykane** [comment] 2019-08-30 21:56
Should be fixed since some releases now

**Closed by jimmykane** 2019-08-30 21:56 UTC

**Comment by mff73** [comment] 2019-09-01 06:13
Hi,
didn't go too much into QS recently :( 
Yes, Units seems now correct :)
Thanks
